# Generated by Django 3.2.3 on 2024-04-07 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('image', models.ImageField(default=None, null=True, upload_to='categories/images/', verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сервиса')),
                ('image', models.ImageField(default=None, null=True, upload_to='services/images/', verbose_name='Ссылка на изображение')),
                ('text', models.TextField(verbose_name='Описание')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость подписки')),
                ('cashback_percentage', models.PositiveIntegerField(verbose_name='Кэшбэк (в процентах)')),
                ('new', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('partners_link', models.TextField(validators=[django.core.validators.URLValidator()], verbose_name='сайт партнера')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autopayment', models.BooleanField(default=False, verbose_name='автоплатеж')),
                ('activation_status', models.PositiveSmallIntegerField(choices=[(1, 'Активирована'), (2, 'недействительна'), (3, 'ожидает активации')], verbose_name='Статус активации подписки')),
                ('promo_code', models.CharField(blank=True, max_length=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('trial', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='services.service')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
