# Generated by Django 3.2.3 on 2024-03-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_auto_20240325_0108"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="subscribed_date",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="services/images/",
                verbose_name="Ссылка на изображение",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="promo_code",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="text",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
