# Generated by Django 3.2.3 on 2024-04-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='payment_status',
            new_name='trial',
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cashback_percentage',
            field=models.PositiveIntegerField(default=5, verbose_name='Кэшбэк (в процентах)'),
            preserve_default=False,
        ),
    ]
