# Generated by Django 3.2.3 on 2024-04-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20240404_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='autopayment',
            field=models.BooleanField(default=False, verbose_name='автоплатеж'),
        ),
    ]
