# Generated by Django 3.2.3 on 2024-03-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название сервиса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cashback', models.PositiveIntegerField(verbose_name='Кэшбэк (в процентах)')),
            ],
            options={
                'verbose_name': 'Тариф',
                'ordering': ('-kind__cost_per_month',),
            },
        ),
        migrations.CreateModel(
            name='TariffKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность подписки в месяцах ')),
                ('cost_per_month', models.PositiveIntegerField(verbose_name='Стоимость в месяц')),
                ('comment_1', models.TextField(verbose_name='Инфо порядок оплаты')),
                ('comment_2', models.PositiveIntegerField(verbose_name='Инфо стоимость далее')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_kinds', to='payments.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Разновидность тарифа',
                'ordering': ('-duration',),
            },
        ),
        migrations.AddField(
            model_name='tariff',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariffs', to='payments.tariffkind', verbose_name='Разновидность тарифа по длительности'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Сервис'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(verbose_name='Общая стоимость')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='Номер телефона')),
                ('accept_rules', models.BooleanField(default=False, verbose_name='Согласие с правилами')),
                ('callback', models.CharField(choices=[('accepted', 'Принят'), ('denied', 'Отклонен')], max_length=10, verbose_name='Ответ от банка')),
                ('payment_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата оплаты')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Сервис')),
                ('tariff_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.tariffkind', verbose_name='Выбранный тариф')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbacks', to='payments.payment', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Кешбэк',
            },
        ),
    ]
