# Generated by Django 3.2.3 on 2024-03-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffkind',
            options={'ordering': ('-cost_per_month',), 'verbose_name': 'Разновидность тарифа'},
        ),
        migrations.RemoveField(
            model_name='tariffkind',
            name='tariff',
        ),
        migrations.AddField(
            model_name='tariffkind',
            name='cashback',
            field=models.PositiveIntegerField(default=5, verbose_name='Кэшбэк (в процентах)'),
        ),
        migrations.AddField(
            model_name='tariffkind',
            name='cost_total',
            field=models.IntegerField(default=199, verbose_name='Стоимость за период'),
        ),
        migrations.AddField(
            model_name='tariffkind',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание тарифа'),
        ),
        migrations.AddField(
            model_name='tariffkind',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Название тарифа'),
        ),
        migrations.AddField(
            model_name='tariffkind',
            name='service',
            field=models.ManyToManyField(to='services.Service', verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='tariffkind',
            name='comment_1',
            field=models.TextField(null=True, verbose_name='Частота оплаты'),
        ),
        migrations.AlterField(
            model_name='tariffkind',
            name='comment_2',
            field=models.TextField(null=True, verbose_name='Стоимость далее'),
        ),
        migrations.AlterField(
            model_name='tariffkind',
            name='cost_per_month',
            field=models.IntegerField(default=199, verbose_name='Стоимость в месяц'),
        ),
        migrations.AlterField(
            model_name='tariffkind',
            name='duration',
            field=models.PositiveIntegerField(choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], verbose_name='Длительность подписки в месяцах '),
        ),
        migrations.DeleteModel(
            name='Tariff',
        ),
    ]
