# Generated by Django 3.2.3 on 2024-04-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='payment',
            name='callback',
            field=models.BooleanField(default=False, verbose_name='Ответ от банка'),
        ),
    ]
