# Generated by Django 3.2.3 on 2024-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20240413_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='next_payment_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
