# Generated by Django 3.2.3 on 2024-04-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20240404_0321'),
        ('payments', '0004_auto_20240402_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_subscriptions', to='services.subscription', verbose_name='Подписка'),
            preserve_default=False,
        ),
    ]
