# Generated by Django 3.2.3 on 2024-04-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_tariffkind_options'),
        ('payments', '0005_payment_subscription'),
    ]

    operations = [
    ]
