# Generated by Django 3.2.3 on 2024-04-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_next_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
